version: 0.1
phases:
  install:
    commands:
      - npm install -g aws-sam-local
      - sam --version
      - sam validate
      - sam package --template-file template.yml --s3-bucket ippevent-public
                                   --output-template-file SamTemplate.yml
artifacts:
  type: zip
  files:
    - SamTemplate.yml
