AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello World example

Globals:
  Function:
    Runtime: nodejs6.10
    Timeout: 180
    Handler: index.handler
    AutoPublishAlias: live
    DeploymentPreference:
      Type: AllAtOnce

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /HelloWorld
            Method: GET
